# Generated by Django 3.1.5 on 2021-02-01 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweetening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('style', models.CharField(choices=[('P', 'Plain'), ('S', 'Sugar'), ('A', 'Almond Milk & Sugar'), ('M', 'Soy Milk & Sugar')], default='P', max_length=1)),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tea')),
            ],
        ),
    ]
