# Generated by Django 3.1.5 on 2021-02-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_sweetening'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sweetening',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='tea',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='sweetening',
            name='date',
            field=models.DateField(verbose_name='Tea time'),
        ),
    ]
