# Generated by Django 3.1.5 on 2021-02-05 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210203_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='cups',
            field=models.ManyToManyField(to='main_app.Cup'),
        ),
    ]
